version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: outbox-postgres
    environment:
      POSTGRES_DB: outbox_db
      POSTGRES_USER: outbox_user
      POSTGRES_PASSWORD: outbox_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U outbox_user -d outbox_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
    driver: local